// Mocks generated by Mockito 5.0.15 from annotations
// in currency_charts/test/presentation/bloc/currency/currency_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:currency_charts/domain/entities/currency.dart' as _i7;
import 'package:currency_charts/domain/repositories/currency_repository.dart'
    as _i2;
import 'package:currency_charts/domain/usecases/get_currencies_data.dart'
    as _i4;
import 'package:currency_charts/utils/failures.dart' as _i6;
import 'package:currency_charts/utils/interval.dart' as _i8;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeCurrencyRepository_0 extends _i1.Fake
    implements _i2.CurrencyRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetCurrenciesData].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrenciesData extends _i1.Mock implements _i4.GetCurrenciesData {
  MockGetCurrenciesData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CurrencyRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeCurrencyRepository_0()) as _i2.CurrencyRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Currency>> execute(
          _i8.ChartsInterval? interval) =>
      (super.noSuchMethod(Invocation.method(#execute, [interval]),
              returnValue: Future<_i3.Either<_i6.Failure, _i7.Currency>>.value(
                  _FakeEither_1<_i6.Failure, _i7.Currency>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.Currency>>);
  @override
  String toString() => super.toString();
}
