// Mocks generated by Mockito 5.0.15 from annotations
// in currency_charts/test/domain/usecases/get_currencies_data_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:currency_charts/domain/entities/currency.dart' as _i6;
import 'package:currency_charts/domain/repositories/currency_repository.dart'
    as _i3;
import 'package:currency_charts/utils/failures.dart' as _i5;
import 'package:currency_charts/utils/interval.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [CurrencyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyRepository extends _i1.Mock
    implements _i3.CurrencyRepository {
  MockCurrencyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Currency>> getCurrenciesData(
          {_i7.ChartsInterval? interval}) =>
      (super.noSuchMethod(
              Invocation.method(#getCurrenciesData, [], {#interval: interval}),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Currency>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Currency>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Currency>>);
  @override
  String toString() => super.toString();
}
